FROM docker.io/library/rust:1.93.0-bookworm@sha256:7274e0edb5b47eda8053b350ebf3d489f7e0f65d2d7e77b16076299c7c047c28 AS builder

WORKDIR /build
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --locked --release

FROM docker.io/library/debian:bookworm-slim@sha256:63a496b5d3b99214b39f5ed70eb71a61e590a77979c79cbee4faf991f8c0783e

WORKDIR /app
COPY --from=builder /build/target/release/plain-axum-order-authorization /app/server

USER 65532:65532
EXPOSE 3000
ENTRYPOINT ["/app/server"]
